[package]
name = "Palindromo"
version = "0.1.0"
authors = ["BoingDeFresa <170113@upslp.edu.mx>"]
edition = "2018"
[[bin]]
name = "RE"
path = "src/170113-palindromo.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
